services:
    ollama:
        # Ollama AI model, accessed via API only
        image: ollama/ollama
        restart: unless-stopped
        ports:
            - "11434:11434"
        environment:
            - OLLAMA_KEEP_ALIVE=3h
        entrypoint:
            [
                "/bin/bash",
                "-c",
                "ollama serve & sleep 5 && ollama pull ${OLLAMA_MODEL} && wait",
            ]
        volumes:
            - ollama-storage:/root/.ollama

    chat-backend:
        # Main backend service
        build: ./chat-backend
        ports:
            - "5050:5000"
        volumes:
            - chat-data:/data

    db-backend:
        # Database service
        build: ./db-backend
        ports:
            - "5432:5432"

    frontend:
        # Frontend UI
        build: ./frontend
        ports:
            - "3000:3000"

volumes:
    ollama-storage:
    chat-data:
