services:
    db-backend:
        # Database service
        build: ./db-backend
        depends_on:
            - mongo
    mongo:
        # MongoDB service
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
