name: Deploy

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    name: Run deploy script
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x scripts/deploy.sh

      - name: Run deploy script
        run: ./scripts/deploy.sh
